server:
  port: 8091
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/library54_db
    username: carrentaluser
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

file:
  uploaddir: 'C:\Users\Yahya\IdeaProjects\library54\images'

logging:
  file:
    name: logs/L54.log
  pattern:
    file: "%d %-5level [%thread] %logger:%msg%n"

  level:
    '[org.springframework.web]': INFO
    '[org.hibernate]': INFO
    '[com.library54]': DEBUG

  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB

L54:
  app:
    jwtSecret: library@55
    jwtExpirationMs: 86400000
